import { useCallback,useEffect,useState } from 'react'
import { useParams,useLocation,Link,useNavigate } from 'react-router-dom'
import { getDeal } from '../../api/deals'
import { friendlyError } from '../../lib/errors'
import Spinner from '../../components/ui/Spinner'
import ActivityTimeline from '../activities/ActivityTimeline'
const stages=['new','contacted','proposal','negotiation','won','lost']
const tempStyle={hot:'temp-pill temp-hot',warm:'temp-pill temp-warm',cold:'temp-pill temp-cold'}
function money(n){return new Intl.NumberFormat('en-LK',{style:'currency',currency:'LKR',maximumFractionDigits:0}).format(n||0)}
export default function DealDetailPage(){const {id}=useParams(),loc=useLocation(),navigate=useNavigate(),carried=loc.state?.deal;const [deal,setDeal]=useState(carried||null),[loading,setLoading]=useState(!carried),[error,setError]=useState(null)
 const load=useCallback(()=>{setLoading(true);setError(null);getDeal(id).then(d=>{if(!d)throw new Error('Not found');setDeal({...carried,...d})}).catch(e=>setError(friendlyError(e))).finally(()=>setLoading(false))},[id])
 useEffect(()=>{load()},[load]); if(loading&&!deal)return <Spinner label="Loading deal"/>; if(error||!deal)return <div className="max-w-2xl space-y-3"><p role="alert" className="alert-error">{error||"We couldn't find that deal."}</p><Link to="/pipeline" className="text-signal underline text-sm">Back to pipeline</Link></div>
 return <section className="page-space max-w-4xl"><button type="button" onClick={()=>navigate('/pipeline')} className="text-xs text-slate-400 hover:text-slate-700">← Back to pipeline</button><div className="crm-card mt-3 p-6 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="crm-section-label">Deal detail</p><h1 className="crm-page-heading mt-1">{deal.title}</h1><p className="mt-1 text-sm text-slate-500">{deal.companyNameSnapshot||'Unknown company'}{deal.contactNameSnapshot&&` · ${deal.contactNameSnapshot}`}</p></div><div className="flex items-center gap-2"><span className="status-pill">{deal.stage}</span>{deal.temperature&&<span className={tempStyle[deal.temperature]}>{deal.temperature}</span>}{deal.isStuck&&<span className="stuck-pill" title="No stage change in 14+ days">Stuck · {deal.stuckDays}d</span>}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="detail-stat"><span>Value</span><strong>{money(deal.value)}</strong></div><div className="detail-stat"><span>Owner</span><strong>{deal.ownerNameSnapshot||'Unassigned'}</strong></div><div className="detail-stat"><span>Stage age</span><strong>{deal.stuckDays} days</strong></div></div><div className="mt-6"><p className="crm-section-label">Stage history</p><div className="mt-3 flex flex-wrap gap-2">{stages.map(s=><span key={s} className={`stage-chip ${s===deal.stage?'is-current':''}`}>{s}</span>)}</div></div></div><ActivityTimeline dealId={deal.id} onActivityLogged={()=>load()}/></section>
}
