import { useCallback, useEffect, useState } from 'react'
import { listActivities, createActivity } from '../../api/activities'
import { friendlyError } from '../../lib/errors'
import Button from '../../components/ui/Button'
const TYPES = [{ value:'call', label:'Call' },{ value:'email', label:'Email' },{ value:'meeting', label:'Meeting' },{ value:'note', label:'Note' }]
const TYPE_ICON = { call:'↗', email:'@', meeting:'◷', note:'—', stage_change:'↻' }
const TYPE_LABEL = { stage_change:'Stage change' }
function typeLabel(type){ return TYPE_LABEL[type] || type.charAt(0).toUpperCase()+type.slice(1) }
function timeAgo(iso){ const mins=Math.round((Date.now()-new Date(iso).getTime())/60000); if(mins<1)return'just now'; if(mins<60)return`${mins}m ago`; const hours=Math.round(mins/60); if(hours<24)return`${hours}h ago`; return`${Math.round(hours/24)}d ago` }
export default function ActivityTimeline({ dealId, contactId }){
 const [activities,setActivities]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[type,setType]=useState('call'),[notes,setNotes]=useState(''),[formError,setFormError]=useState(null),[saving,setSaving]=useState(false)
 const load=useCallback(()=>{setLoading(true);setError(null);listActivities({dealId,contactId}).then(res=>setActivities(res.data)).catch(err=>setError(friendlyError(err))).finally(()=>setLoading(false))},[dealId,contactId]); useEffect(()=>{load()},[load])
 const submit=async(e)=>{e.preventDefault();setFormError(null);const trimmedNotes=notes.trim();if(!trimmedNotes){setFormError('Add a note before saving.');return}setSaving(true);try{const submitted={type,notes:trimmedNotes,dealId,contactId};const created=await createActivity(submitted);setActivities([{...submitted,...created},...activities]);setNotes('')}catch(err){setFormError(friendlyError(err))}finally{setSaving(false)}}
 return <div className="crm-card p-6 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="crm-section-label">Customer history</p><h2 className="mt-1 font-display text-lg font-semibold text-slate-950">Activity</h2></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-500">{activities.length} events</span></div>
 <form onSubmit={submit} className="mb-6 rounded-2xl border border-slate-100 bg-slate-50/80 p-3">{formError&&<p role="alert" className="mb-2 rounded-lg bg-red-50 px-3 py-2 text-xs text-red-700">{formError}</p>}<div className="flex flex-col gap-2 sm:flex-row"><select value={type} onChange={e=>setType(e.target.value)} className="crm-input sm:w-32"><option value="call">Call</option><option value="email">Email</option><option value="meeting">Meeting</option><option value="note">Note</option></select><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add an activity note…" className="crm-input flex-1"/><Button type="submit" size="sm" busy={saving} busyLabel="Saving…">Log activity</Button></div></form>
 {error&&<p role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}
 {loading?<p className="py-6 text-sm text-slate-400">Loading activity…</p>:activities.length===0?<div className="rounded-2xl border border-dashed border-slate-200 py-10 text-center"><div className="text-sm font-medium text-slate-700">No activity yet</div><p className="mt-1 text-xs text-slate-400">Log the first customer interaction above.</p></div>:<ul className="relative space-y-5 pl-2">{activities.map(a=><li key={a.id} className="relative flex gap-3"><span className="relative z-10 grid h-8 w-8 shrink-0 place-items-center rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-500 shadow-sm">{TYPE_ICON[a.type]||'•'}</span><div className="min-w-0 flex-1 border-b border-slate-100 pb-5 last:border-0"><div className="flex items-center justify-between gap-3"><span className="text-sm font-semibold text-slate-800">{typeLabel(a.type)}{a.type==='stage_change'&&<span className="ml-2 text-[10px] font-normal text-slate-400">automatic</span>}</span><span className="shrink-0 text-[10px] text-slate-400 tabular">{timeAgo(a.loggedAt)}</span></div><p className="mt-1 text-sm leading-6 text-slate-500">{a.notes}</p></div></li>)}</ul>}
 </div>
}
