import { useEffect,useState } from 'react'
import { getCampaignRoi } from '../api/dashboard'
import { friendlyError } from '../lib/errors'
import Spinner from '../components/ui/Spinner'
import Button from '../components/ui/Button'
const SOURCES=['Google Ads','LinkedIn','Email Campaign','Referral','Other']
function dates(range){const now=new Date();if(range==='month'){const start=new Date(now.getFullYear(),now.getMonth()-1,1);const end=new Date(now.getFullYear(),now.getMonth(),1);return {startDate:start.toISOString().slice(0,10),endDate:end.toISOString().slice(0,10)}}if(range==='quarter'){const start=new Date(now.getFullYear(),now.getMonth()-3,1);const end=new Date(now.getFullYear(),now.getMonth(),1);return {startDate:start.toISOString().slice(0,10),endDate:end.toISOString().slice(0,10)}}return {startDate:'',endDate:''}}
export default function CampaignDashboardPage(){const [range,setRange]=useState('month'),[custom,setCustom]=useState({startDate:'',endDate:''}),[data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null)
 const load=()=>{setLoading(true);setError(null);const d=range==='custom'?custom:dates(range);getCampaignRoi(d).then(r=>setData(r.data||[])).catch(e=>setError(friendlyError(e))).finally(()=>setLoading(false))};useEffect(load,[range])
 return <section className="page-space"><div className="page-header"><div><p className="crm-section-label">Marketing intelligence</p><h1 className="crm-page-heading">Campaign conversion</h1><p className="page-subtitle">Compare lead sources using leads created in the selected period.</p></div></div><div className="s2-panel dashboard-toolbar"><div className="range-buttons">{[['month','Last Month'],['quarter','Last Quarter'],['custom','Custom']].map(([v,l])=><button key={v} className={range===v?'active':''} onClick={()=>setRange(v)}>{l}</button>)}</div>{range==='custom'&&<div className="date-inputs"><input type="date" value={custom.startDate} onChange={e=>setCustom({...custom,startDate:e.target.value})}/><input type="date" value={custom.endDate} onChange={e=>setCustom({...custom,endDate:e.target.value})}/><Button size="sm" onClick={load}>Apply</Button></div>}</div>{error&&<p role="alert" className="alert-error">{error}</p>}{loading?<Spinner label="Loading campaign report"/>:<div className="s2-panel mt-3 overflow-x-auto"><table className="campaign-table"><thead><tr><th>Source</th><th>Total leads</th><th>Converted to deal</th><th>Conversion</th></tr></thead><tbody>{SOURCES.map(source=>{const r=data.find(x=>x.source===source)||{totalLeads:0,convertedLeads:0,conversionRate:0};return <tr key={source}><td><strong>{source}</strong></td><td>{r.totalLeads}</td><td>{r.convertedLeads}</td><td>{r.conversionRate}%</td></tr>})}</tbody></table></div>}</section>}
